services:
  celery-worker:
    container_name: celery-worker
    build:
      context: ../../
      dockerfile: .devops/Dockerfile
    restart: unless-stopped  
    command: 
      sh -c "celery -A core worker --loglevel=info"
    networks:
      - main_network
    
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - main_network
    depends_on:
      - nurcrm_database

  nurcrm_database: 
    image: postgres:15-alpine
    container_name: nurcrm_database
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - ../../storage:/var/lib/postgresql/data
    networks:
      - main_network

  django:
    container_name: django
    build:
      context: ../../
      dockerfile: .devops/Dockerfile
    command: 
      sh -c "python manage.py makemigrations users barber booking cafe consalting construction education instagram logistics main storehouse whatsapp && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
      # gunicorn core.wsgi:application --bind 0.0.0.0:8000" # Для прода gunicorn (Многопоточный)
    ports: 
      - "8000:8000"
    depends_on:
      - nurcrm_database
      - redis
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
